services:
  db:
    image: postgres:13
    container_name: kittygram_db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: kittygram_backend
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    restart: always

  frontend:
    build: ./frontend
    container_name: kittygram_frontend
    depends_on:
      - backend
    restart: always

  gateway:
    build: ./nginx
    container_name: kittygram_gateway
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - static_data:/static
      - media_data:/media
    restart: always

volumes:
  pg_data:
  static_data:
  media_data: